- resources/views/components/layout.blade.php
Hi there - this meta tag was not present in the layout file - maybe by mistake? The site looked strange on the phone for that reason.
> bring back meta viewport tag for responsiveness

- database/migrations/2021_05_15_142833_unique_youtube_id_in_streams_table.php
This adds a unique constraint to the `youtube_id` field in the streams table, this way streams cannot be added several times.
> Add unique constraint to stream youtube id

- resources/views/components/layout.blade.php
Apparently self-closing script tags are invalid html and can cause browsers to wrongly interpret the html.
More info here: https://stackoverflow.com/questions/69913/why-dont-self-closing-script-elements-work
In my case, my Adblocker (AdGuard) tried to block Fathom Analytics, causing the entire script tag to fail loading, resulting in Livewire not working.
> Correctly close self-closing script tag

- app/Models/Stream.php
The dates property is deprecated, it is recommended that the casts property is used, this PR does that.
> Replace deprecated dates property with casts

- app/Http/Controllers/CalendarController.php
- app/Models/Stream.php
- composer.json
- composer.lock
- routes/web.php
- tests/Feature/CalendarTest.php
This PR adds a `calendar.ics` route which returns a calendar - you can add this URL to your Calendar app to get all streams in your calendar.
> add calendar route

- app/Http/Controllers/CalendarController.php
- app/Models/Stream.php
- tests/Feature/CalendarTest.php
Currently the CalendarController adds all streams to the calendar. This isn't a huge problem yet but in the future there will be a huge amount of streams added to the calendar for no real reason.
I also updated the `upcoming` scope to return all streams starting at the exact start of the day (2020-05-17 00:00:00) instead of 2020-05-17 00:00:01.
> Add only upcoming events to the calendar

- resources/views/pages/partials/stream.blade.php
The YouTube thumbnail preview images are broken on safari due to some flex issues. As a "quick fix" I just wrapped the image inside a div, maybe there is a better solution.
Before
After
> Fix image aspect ratio on safari

- tests/TestCase.php
- tests/Unit/YoutubeTest.php
The default behavior in all tests:
YouTube API Key will be overwritten with a fake one.
If there is a need to run a test against the real API simply call:
`$this->useRealYoutubeApi()` in your test
> Never ever hit the real api during tests

- app/Models/Stream.php
- app/Providers/AppServiceProvider.php
- app/View/Components/AddStreamsToCalendar.php
- public/css/app.css
- public/mix-manifest.json
- resources/css/app.css
- resources/views/components/add-streams-to-calendar.blade.php
- resources/views/components/icons/calendar.blade.php
- resources/views/components/icons/chevron-down.blade.php
- resources/views/components/icons/download.blade.php
- resources/views/components/layout.blade.php
- resources/views/pages/partials/stream.blade.php
This PR adds the possibility to subscribe to the calendar or specific events using `webcal`.
Depending on the device and operating system the calendar will automatically be added to the default calendar application (Mac, iPhone) or the browser will ask for the calendar application (Windows).
As fallback (if webcal is not supported) the .ics files can still be downloaded as currently implemented.
I did a bit of frontend work which looks like this
I marked this one as a draft since there is probably some refactoring required.
> Add webcal links for streams

- app/Actions/PrepareStreams.php
- app/Actions/SortStreamsByDateAction.php
- app/Http/Controllers/ArchiveController.php
- app/Http/Controllers/PageHomeController.php
- app/Http/Livewire/StreamList.php
- database/seeders/TestDataSeeder.php
- resources/views/livewire/stream-list.blade.php
- resources/views/pages/archive.blade.php
- resources/views/pages/home.blade.php
- tests/Feature/PrepareStreamsTest.php
Hi Christoph, 
I saw on the stream that you wanted to add pagination so i took a crack at it with this pull requests. 
I though the best way to do it is by retrieving the Steams in the livewire component instead of the Controllers. (Because that way livewire can paginate). 
Take a look at the changes if you like. Don't know if i did it the way you would like to structure things. 
Some things to consider: 
- Styling on the pagination links needs some work. 
- When clicking a pagination link it's doesn't scroll back to the top. 
- Maybe use a different qty per page.
- I marked one test as skipped because i removed the method from PrepareStreams (it was no longer used). So maybe another test needs to be written in place?
> Add Pagination

- app/Console/Commands/CheckIfUpcomingStreamsAreLiveCommand.php
- tests/Feature/Commands/CheckIfUpcomingStreamsAreLiveCommandTest.php
- tests/Feature/Commands/UpdateUpcomingStreamsCommandTest.php
@christophrumpel I have added some additional testcases and a `->approved()` check on the `CheckIfUpcomingStreamsAreLiveCommand` because i think you only want to update the approved their right?
> Update Youtube Testcases

- app/Jobs/ImportYoutubeChannelStreamsJob.php
- tests/Feature/Commands/TweetAboutLiveStreamsCommandTest.php
- tests/Feature/ImportYoutubeChannelStreamsTest.php
When importing the streams for the channel you want to add the **Model Channel id** to the Stream; not the **ChannelId** from **Youtube** because of the relationship with your own channels. This way the tweets will include the twitter handle if set. 
Another way to fix this is changing the relation on the Stream model to: 
```php
public function channel(): BelongsTo
{
return $this->belongsTo(Channel::class, 'channel_id', 'platform_id');
}
````
We might also want to change the database column type on the streams table to match the channel_id on the channels table.
> Fix bug with not adding twitter handle for channels

- app/Console/Commands/UpdateUpcomingStreamsCommand.php
- tests/Feature/Commands/UpdateUpcomingStreamsCommandTest.php
This PR fixes #79.
I think this task should be in the `UpdateUpcomingStreamsCommand` because this is responsible for checking upcoming streams. I adapted the command (similar to the `UpdateLiveAndFinishedStreamsCommand`) so that we can handle streams where there is no response from Youtube anymore.
Can you take a look @spaantje?
> Fix - Delete streams where the video is not given anymore

- database/migrations/2021_10_23_073416_update_stream_status_none_to_finished.php
Referencing the model itself or other platform code in migrations is dangerous as should the model be renamed or even remoed the migration would no longer work or should a constant change the migration might behave different than was intended. This PR updates the migrations to use the `DB` `QueryBuilder` instead of the `Eloquent` one to avoid these Problems.
> Do not reference models and platform code in migrations

- app/Providers/AppServiceProvider.php
- app/Services/YouTubeClient.php
Hey @christophrumpel, as the title implies this is v2 of the implementation, looking at the code I think I found the issue. I forgot actually merging the parameters with the key when calling `array_merge`. I compared the generated urls with each other and they're now identical so I think this should work now.
https://github.com/christophrumpel/larastreamers/blob/f9dda0c697b2e3f020f26d5db62d3b2c52f4c5a7/app/Providers/AppServiceProvider.php#L21-L23
> Use Http macro to avoid calling configuration in class v2

- app/Models/Stream.php
The feed was setting the stream name as the author name, so you'd get this:
```xml
<author>
<name>
<![CDATA[ Laravel Livewire: How Does It Work? 🧐 ]]>
</name>
</author>
```
But that's already specified in the `<title></title>` tags. This PR changes it to use the name of the related channel, so you get:
```xml
<author>
<name>
<![CDATA[ Christoph Rumpel ]]>
</name>
</author>
```
This issue was mentioned in the discussion [here](https://github.com/christophrumpel/larastreamers/discussions/127#discussioncomment-1772453).
> use channel name in feed

- resources/views/components/search.blade.php
I noticed that the border style is slightly wrong on the focused select field.
Before:
After:
> Fix border radius on select

- app/Http/Livewire/StreamListArchive.php
- tests/Feature/PageArchiveTest.php
On the archive page, streamers are currently sorted by id. This PR changes the order by name which in my opinion is way easier.
Before:
After:
> Order streamer list by name

- app/Http/Livewire/StreamListArchive.php
- tests/Feature/Http/Livewire/StreamListArchiveTest.php
- tests/Feature/PageArchiveTest.php
Fixes #158 
Streamers were showing as filterable on the Archive page despite having no finished streams, so when you filtered the archive by them, nothing showed up.
> prevent streamers with no finished streams from showing

- app/Console/Commands/TweetAboutWeeklySummaryCommand.php
- tests/Feature/Commands/TweetAboutWeeklySummaryCommandTest.php
This is a small update to the Tweet that sends out as a summary. Previously, if only 1 Stream was found, the following would be Tweeted:
> There were 1 streams last week. 👏 Thanks to all the streamers and viewers. 🙏🏻
There's no account for pluralisation, so this PR changes it to be:
> 1 stream happened last week. 👏 Thanks to all the streamers and viewers. 🙏🏻
and then if it's more than one:
> 2 streams happened last week. 👏 Thanks to all the streamers and viewers. 🙏🏻
> 3 streams happened last week. 👏 Thanks to all the streamers and viewers. 🙏🏻
etc, etc
Fixes #175
> update summary tweet pluralisation

- app/Http/Livewire/StreamListArchive.php
- tests/Feature/Http/Livewire/StreamListArchiveTest.php
This PR fixes #165 by resetting the page when the streamer property is updated just like it was already done with the search property.
I tried to add a test but I messing around with the page property on the class directly doesn't behave like expected. Maybe there is something I am missing.
> Reset page when streamer property is updated

- resources/views/components/streamer-channel.blade.php
This PR updates the link section of the streamer channel card to always be positioned at the very bottom of the card. I think this way it looks way cleaner.
Before
After
> Fix alignment

- app/Http/Livewire/StreamListArchive.php
- resources/views/components/search.blade.php
- resources/views/livewire/stream-list-archive.blade.php
- resources/views/pages/streamers.blade.php
- tests/Feature/Http/Livewire/StreamListArchiveTest.php
Fixes https://github.com/christophrumpel/larastreamers/issues/249
Adds a count into the header of the Archive page:
Along with a count for each Streamer in the search dropdown:
I've also added a count to the main Streamers page too, just for consistency and I think it would be nice to watch that number grow:
> add stream count to archive page
